"""Données par métier : codes NAF (SIRENE), tags OpenStreetMap, contenu des maquettes et idées de publications."""

HORAIRES_ARTISAN = {"Lundi – Vendredi": "8h – 18h", "Samedi": "Sur rendez-vous", "Dimanche": "Fermé"}
HORAIRES_BOUTIQUE = {"Mardi – Vendredi": "9h – 19h", "Samedi": "9h – 18h", "Dimanche – Lundi": "Fermé"}

METIERS = {
    "plombier": {
        "libelle": "Plombier chauffagiste",
        "naf": ["43.22A"],
        "osm": [("craft", "plumber"), ("craft", "hvac")],
        "schema": "Plumber",
        "couleur": "#0b63ce",
        "accroche": "Fuite, chauffe-eau, débouchage, salle de bain : un artisan local, réactif, qui annonce le prix avant d'intervenir.",
        "badges": ["Devis gratuit", "Intervention rapide", "Artisan local"],
        "services": [
            ("Dépannage", "Fuites, canalisations bouchées, WC : intervention rapide."),
            ("Chauffe-eau", "Remplacement et entretien de ballons électriques et thermodynamiques."),
            ("Salle de bain", "Rénovation, douche à l'italienne, robinetterie."),
            ("Chauffage", "Entretien de chaudière, radiateurs, désembouage."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Par grand froid, protégez vos canalisations extérieures et gardez un filet de chauffage dans les pièces inoccupées pour éviter le gel.",
            "printemps": "Le printemps est le bon moment pour détartrer votre chauffe-eau : moins de consommation et une durée de vie prolongée.",
            "ete": "Avant de partir en vacances, coupez l'arrivée d'eau générale : c'est la meilleure assurance contre les dégâts des eaux.",
            "automne": "Pensez à l'entretien annuel de votre chaudière avant l'hiver : il est obligatoire et évite les pannes au premier froid.",
        },
    },
    "electricien": {
        "libelle": "Électricien",
        "naf": ["43.21A"],
        "osm": [("craft", "electrician")],
        "schema": "Electrician",
        "couleur": "#e0a100",
        "accroche": "Dépannage, mise aux normes, rénovation électrique : un électricien local, sérieux et joignable.",
        "badges": ["Devis gratuit", "Mise aux normes", "Artisan local"],
        "services": [
            ("Dépannage", "Panne de courant, disjoncteur qui saute, prises hors service."),
            ("Mise aux normes", "Tableau électrique, mise en sécurité, diagnostics."),
            ("Rénovation", "Installation complète, éclairage, domotique."),
            ("Bornes de recharge", "Installation de bornes pour véhicule électrique."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Radiateurs d'appoint et multiprises ne font pas bon ménage : branchez-les directement au mur pour éviter la surchauffe.",
            "printemps": "Testez votre disjoncteur différentiel une fois par an avec le bouton « test » : il protège votre famille.",
            "ete": "Orage annoncé ? Débranchez box internet et électronique sensible, ou faites installer un parafoudre.",
            "automne": "Les jours raccourcissent : c'est le moment de passer à l'éclairage LED et de contrôler vos installations extérieures.",
        },
    },
    "peintre": {
        "libelle": "Peintre en bâtiment",
        "naf": ["43.34Z"],
        "osm": [("craft", "painter")],
        "schema": "HousePainter",
        "couleur": "#c2410c",
        "accroche": "Peinture intérieure et extérieure, ravalement, revêtements : un travail propre, dans les délais annoncés.",
        "badges": ["Devis gratuit", "Chantier propre", "Artisan local"],
        "services": [
            ("Peinture intérieure", "Murs, plafonds, boiseries, finitions soignées."),
            ("Façades", "Ravalement, nettoyage et peinture de façade."),
            ("Revêtements", "Papier peint, toile de verre, enduits décoratifs."),
            ("Rénovation", "Remise en état après location ou avant une vente."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "L'hiver est idéal pour les travaux de peinture intérieure : les plannings sont plus souples qu'au printemps.",
            "printemps": "Une façade se peint entre 10 et 25 °C, sans pluie annoncée : réservez votre créneau tôt.",
            "ete": "Chaleur et plein soleil font sécher la peinture trop vite : les travaux extérieurs se font tôt le matin.",
            "automne": "Avant l'hiver, vérifiez les fissures de votre façade : les réparer maintenant évite les infiltrations.",
        },
    },
    "menuisier": {
        "libelle": "Menuisier",
        "naf": ["43.32A", "16.23Z"],
        "osm": [("craft", "carpenter"), ("craft", "joiner")],
        "schema": "HomeAndConstructionBusiness",
        "couleur": "#8a5a2b",
        "accroche": "Fenêtres, portes, placards et agencements sur mesure : le savoir-faire d'un menuisier local.",
        "badges": ["Sur mesure", "Devis gratuit", "Artisan local"],
        "services": [
            ("Fenêtres et portes", "Pose et remplacement, bois, PVC, aluminium."),
            ("Agencement", "Placards, dressings, bibliothèques sur mesure."),
            ("Escaliers", "Fabrication et rénovation d'escaliers."),
            ("Terrasses", "Terrasses et aménagements extérieurs en bois."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Des fenêtres qui laissent passer l'air, c'est jusqu'à 15 % de chauffage perdu : un réglage suffit parfois.",
            "printemps": "Une terrasse en bois s'entretient au printemps : nettoyage puis saturateur pour la protéger toute l'année.",
            "ete": "L'été est le bon moment pour préparer vos projets d'agencement de la rentrée : les délais de fabrication comptent.",
            "automne": "Avant le froid, vérifiez les joints de vos portes et fenêtres : c'est simple et ça change tout.",
        },
    },
    "couvreur": {
        "libelle": "Couvreur",
        "naf": ["43.91B"],
        "osm": [("craft", "roofer")],
        "schema": "RoofingContractor",
        "couleur": "#b91c1c",
        "accroche": "Réparation, rénovation et entretien de toiture : un couvreur local qui intervient vite après une intempérie.",
        "badges": ["Devis gratuit", "Urgences intempéries", "Artisan local"],
        "services": [
            ("Réparation", "Tuiles cassées, fuites, recherche d'infiltrations."),
            ("Rénovation", "Réfection complète de toiture, isolation."),
            ("Zinguerie", "Gouttières, chéneaux, descentes d'eau pluviale."),
            ("Entretien", "Démoussage, nettoyage, traitement hydrofuge."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Après une tempête, faites vérifier votre toiture : une tuile déplacée peut causer une infiltration des semaines plus tard.",
            "printemps": "Le printemps est la saison idéale pour le démoussage : la mousse retient l'eau et abîme les tuiles.",
            "ete": "Profitez de l'été pour isoler vos combles : c'est le premier poste de déperdition de chaleur d'une maison.",
            "automne": "Nettoyez vos gouttières après la chute des feuilles : bouchées, elles débordent sur vos murs.",
        },
    },
    "coiffeur": {
        "libelle": "Salon de coiffure",
        "naf": ["96.02A"],
        "osm": [("shop", "hairdresser")],
        "schema": "HairSalon",
        "couleur": "#7c3aed",
        "accroche": "Coupe, couleur, soins : un salon de quartier où l'on prend le temps de vous écouter.",
        "badges": ["Sur rendez-vous", "Produits professionnels", "Salon de quartier"],
        "services": [
            ("Coupe", "Femme, homme, enfant, conseils personnalisés."),
            ("Couleur", "Coloration, balayage, mèches, patine."),
            ("Soins", "Soins profonds, lissage, traitements du cuir chevelu."),
            ("Coiffure événement", "Mariage, cérémonie, chignons."),
        ],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {
            "hiver": "Le froid et le chauffage dessèchent les cheveux : un soin hydratant par semaine fait toute la différence.",
            "printemps": "Le printemps est la saison des changements : c'est le moment d'oser la nouvelle coupe ou la nouvelle couleur.",
            "ete": "Soleil, sel et chlore abîment la couleur : protégez vos cheveux comme votre peau.",
            "automne": "La rentrée est idéale pour couper les pointes abîmées par l'été et repartir sur de bonnes bases.",
        },
    },
    "estheticienne": {
        "libelle": "Institut de beauté",
        "naf": ["96.02B"],
        "osm": [("shop", "beauty")],
        "schema": "BeautySalon",
        "couleur": "#db2777",
        "accroche": "Soins du visage, épilation, onglerie, massages : un moment pour vous, près de chez vous.",
        "badges": ["Sur rendez-vous", "Produits de qualité", "Institut de quartier"],
        "services": [
            ("Soins du visage", "Nettoyage, hydratation, soins anti-âge."),
            ("Épilation", "Cire, toutes zones, femme et homme."),
            ("Onglerie", "Manucure, pose de vernis semi-permanent, beauté des pieds."),
            ("Massages", "Massages relaxants et modelages du corps."),
        ],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {
            "hiver": "En hiver, la peau a besoin de plus de nutrition : passez à une crème plus riche et n'oubliez pas les lèvres.",
            "printemps": "Un gommage au printemps prépare la peau à recevoir le soleil et unifie le teint.",
            "ete": "Après le soleil, hydratez votre peau matin et soir : c'est le secret d'un bronzage qui dure.",
            "automne": "L'automne est le moment idéal pour un soin réparateur après les agressions de l'été.",
        },
    },
    "garage": {
        "libelle": "Garage automobile",
        "naf": ["45.20A", "45.20B"],
        "osm": [("shop", "car_repair")],
        "schema": "AutoRepair",
        "couleur": "#1f2937",
        "accroche": "Entretien, réparation, pneus, diagnostic : un garage indépendant, des prix clairs et des délais tenus.",
        "badges": ["Devis gratuit", "Toutes marques", "Garage indépendant"],
        "services": [
            ("Entretien", "Vidange, révision constructeur, filtres."),
            ("Freinage", "Plaquettes, disques, liquide de frein."),
            ("Pneus", "Montage, équilibrage, parallélisme."),
            ("Diagnostic", "Voyant allumé, valise électronique, préparation au contrôle technique."),
        ],
        "horaires": {"Lundi – Vendredi": "8h – 12h / 14h – 18h30", "Samedi": "8h – 12h", "Dimanche": "Fermé"},
        "conseils": {
            "hiver": "Pneus hiver ou 4 saisons : dans de nombreuses communes de montagne, ils sont obligatoires de novembre à mars.",
            "printemps": "Au printemps, faites contrôler votre climatisation avant les premières chaleurs.",
            "ete": "Avant un long trajet : pression des pneus, niveaux et freins. 10 minutes de contrôle pour partir serein.",
            "automne": "Vérifiez votre batterie avant l'hiver : c'est la première cause de panne au premier froid.",
        },
    },
}

SAISONS = {12: "hiver", 1: "hiver", 2: "hiver", 3: "printemps", 4: "printemps", 5: "printemps",
           6: "ete", 7: "ete", 8: "ete", 9: "automne", 10: "automne", 11: "automne"}
