"""Données par métier : codes NAF (SIRENE), tags OpenStreetMap, contenu des maquettes et idées de publications."""
import re


HORAIRES_ARTISAN = {"Lundi – Vendredi": "8h – 18h", "Samedi": "Sur rendez-vous", "Dimanche": "Fermé"}
HORAIRES_BOUTIQUE = {"Mardi – Vendredi": "9h – 19h", "Samedi": "9h – 18h", "Dimanche – Lundi": "Fermé"}

METIERS = {
    "plombier": {
        "mots": ["sanitaire", "plomberie", "plombier", "chauffage", "installations de chauffage", "ferblanterie"],
        "libelle": "Plombier chauffagiste",
        "naf": ["43.22A"],
        "osm": [("craft", "plumber"), ("craft", "hvac")],
        "schema": "Plumber",
        "couleur": "#0b63ce",
        "accroche": "Fuite, chauffe-eau, débouchage, salle de bain : un artisan local, réactif, qui annonce le prix avant d'intervenir.",
        "badges": ["Devis gratuit", "Intervention rapide", "Artisan local"],
        "services": [
            ("Dépannage", "Fuites, canalisations bouchées, WC : intervention rapide."),
            ("Chauffe-eau", "Remplacement et entretien de ballons électriques et thermodynamiques."),
            ("Salle de bain", "Rénovation, douche à l'italienne, robinetterie."),
            ("Chauffage", "Entretien de chaudière, radiateurs, désembouage."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Par grand froid, protégez vos canalisations extérieures et gardez un filet de chauffage dans les pièces inoccupées pour éviter le gel.",
            "printemps": "Le printemps est le bon moment pour détartrer votre chauffe-eau : moins de consommation et une durée de vie prolongée.",
            "ete": "Avant de partir en vacances, coupez l'arrivée d'eau générale : c'est la meilleure assurance contre les dégâts des eaux.",
            "automne": "Pensez à l'entretien annuel de votre chaudière avant l'hiver : il est obligatoire et évite les pannes au premier froid.",
        },
    },
    "electricien": {
        "mots": ["electricite", "electricien", "installations electriques", "domotique", "photovoltaique"],
        "libelle": "Électricien",
        "naf": ["43.21A"],
        "osm": [("craft", "electrician")],
        "schema": "Electrician",
        "couleur": "#e0a100",
        "accroche": "Dépannage, mise aux normes, rénovation électrique : un électricien local, sérieux et joignable.",
        "badges": ["Devis gratuit", "Mise aux normes", "Artisan local"],
        "services": [
            ("Dépannage", "Panne de courant, disjoncteur qui saute, prises hors service."),
            ("Mise aux normes", "Tableau électrique, mise en sécurité, diagnostics."),
            ("Rénovation", "Installation complète, éclairage, domotique."),
            ("Bornes de recharge", "Installation de bornes pour véhicule électrique."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Radiateurs d'appoint et multiprises ne font pas bon ménage : branchez-les directement au mur pour éviter la surchauffe.",
            "printemps": "Testez votre disjoncteur différentiel une fois par an avec le bouton « test » : il protège votre famille.",
            "ete": "Orage annoncé ? Débranchez box internet et électronique sensible, ou faites installer un parafoudre.",
            "automne": "Les jours raccourcissent : c'est le moment de passer à l'éclairage LED et de contrôler vos installations extérieures.",
        },
    },
    "peintre": {
        "mots": ["peinture", "peintre", "platrerie", "gypserie", "decoration interieure"],
        "libelle": "Peintre en bâtiment",
        "naf": ["43.34Z"],
        "osm": [("craft", "painter")],
        "schema": "HousePainter",
        "couleur": "#c2410c",
        "accroche": "Peinture intérieure et extérieure, ravalement, revêtements : un travail propre, dans les délais annoncés.",
        "badges": ["Devis gratuit", "Chantier propre", "Artisan local"],
        "services": [
            ("Peinture intérieure", "Murs, plafonds, boiseries, finitions soignées."),
            ("Façades", "Ravalement, nettoyage et peinture de façade."),
            ("Revêtements", "Papier peint, toile de verre, enduits décoratifs."),
            ("Rénovation", "Remise en état après location ou avant une vente."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "L'hiver est idéal pour les travaux de peinture intérieure : les plannings sont plus souples qu'au printemps.",
            "printemps": "Une façade se peint entre 10 et 25 °C, sans pluie annoncée : réservez votre créneau tôt.",
            "ete": "Chaleur et plein soleil font sécher la peinture trop vite : les travaux extérieurs se font tôt le matin.",
            "automne": "Avant l'hiver, vérifiez les fissures de votre façade : les réparer maintenant évite les infiltrations.",
        },
    },
    "menuisier": {
        "mots": ["menuiserie", "menuisier", "ebenisterie", "charpente", "agencement"],
        "libelle": "Menuisier",
        "naf": ["43.32A", "16.23Z"],
        "osm": [("craft", "carpenter"), ("craft", "joiner")],
        "schema": "HomeAndConstructionBusiness",
        "couleur": "#8a5a2b",
        "accroche": "Fenêtres, portes, placards et agencements sur mesure : le savoir-faire d'un menuisier local.",
        "badges": ["Sur mesure", "Devis gratuit", "Artisan local"],
        "services": [
            ("Fenêtres et portes", "Pose et remplacement, bois, PVC, aluminium."),
            ("Agencement", "Placards, dressings, bibliothèques sur mesure."),
            ("Escaliers", "Fabrication et rénovation d'escaliers."),
            ("Terrasses", "Terrasses et aménagements extérieurs en bois."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Des fenêtres qui laissent passer l'air, c'est jusqu'à 15 % de chauffage perdu : un réglage suffit parfois.",
            "printemps": "Une terrasse en bois s'entretient au printemps : nettoyage puis saturateur pour la protéger toute l'année.",
            "ete": "L'été est le bon moment pour préparer vos projets d'agencement de la rentrée : les délais de fabrication comptent.",
            "automne": "Avant le froid, vérifiez les joints de vos portes et fenêtres : c'est simple et ça change tout.",
        },
    },
    "couvreur": {
        "mots": ["couverture", "couvreur", "toiture", "toitures", "etancheite"],
        "libelle": "Couvreur",
        "naf": ["43.91B"],
        "osm": [("craft", "roofer")],
        "schema": "RoofingContractor",
        "couleur": "#b91c1c",
        "accroche": "Réparation, rénovation et entretien de toiture : un couvreur local qui intervient vite après une intempérie.",
        "badges": ["Devis gratuit", "Urgences intempéries", "Artisan local"],
        "services": [
            ("Réparation", "Tuiles cassées, fuites, recherche d'infiltrations."),
            ("Rénovation", "Réfection complète de toiture, isolation."),
            ("Zinguerie", "Gouttières, chéneaux, descentes d'eau pluviale."),
            ("Entretien", "Démoussage, nettoyage, traitement hydrofuge."),
        ],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {
            "hiver": "Après une tempête, faites vérifier votre toiture : une tuile déplacée peut causer une infiltration des semaines plus tard.",
            "printemps": "Le printemps est la saison idéale pour le démoussage : la mousse retient l'eau et abîme les tuiles.",
            "ete": "Profitez de l'été pour isoler vos combles : c'est le premier poste de déperdition de chaleur d'une maison.",
            "automne": "Nettoyez vos gouttières après la chute des feuilles : bouchées, elles débordent sur vos murs.",
        },
    },
    "coiffeur": {
        "mots": ["coiffure", "coiffeur", "coiffeuse", "barbier", "barber"],
        "libelle": "Salon de coiffure",
        "naf": ["96.02A"],
        "osm": [("shop", "hairdresser")],
        "schema": "HairSalon",
        "couleur": "#7c3aed",
        "accroche": "Coupe, couleur, soins : un salon de quartier où l'on prend le temps de vous écouter.",
        "badges": ["Sur rendez-vous", "Produits professionnels", "Salon de quartier"],
        "services": [
            ("Coupe", "Femme, homme, enfant, conseils personnalisés."),
            ("Couleur", "Coloration, balayage, mèches, patine."),
            ("Soins", "Soins profonds, lissage, traitements du cuir chevelu."),
            ("Coiffure événement", "Mariage, cérémonie, chignons."),
        ],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {
            "hiver": "Le froid et le chauffage dessèchent les cheveux : un soin hydratant par semaine fait toute la différence.",
            "printemps": "Le printemps est la saison des changements : c'est le moment d'oser la nouvelle coupe ou la nouvelle couleur.",
            "ete": "Soleil, sel et chlore abîment la couleur : protégez vos cheveux comme votre peau.",
            "automne": "La rentrée est idéale pour couper les pointes abîmées par l'été et repartir sur de bonnes bases.",
        },
    },
    "estheticienne": {
        "mots": ["esthetique", "estheticienne", "institut de beaute", "beaute", "onglerie", "ongles", "cosmetique", "massage", "maquillage", "soins du corps"],
        "libelle": "Institut de beauté",
        "naf": ["96.02B"],
        "osm": [("shop", "beauty")],
        "schema": "BeautySalon",
        "couleur": "#db2777",
        "accroche": "Soins du visage, épilation, onglerie, massages : un moment pour vous, près de chez vous.",
        "badges": ["Sur rendez-vous", "Produits de qualité", "Institut de quartier"],
        "services": [
            ("Soins du visage", "Nettoyage, hydratation, soins anti-âge."),
            ("Épilation", "Cire, toutes zones, femme et homme."),
            ("Onglerie", "Manucure, pose de vernis semi-permanent, beauté des pieds."),
            ("Massages", "Massages relaxants et modelages du corps."),
        ],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {
            "hiver": "En hiver, la peau a besoin de plus de nutrition : passez à une crème plus riche et n'oubliez pas les lèvres.",
            "printemps": "Un gommage au printemps prépare la peau à recevoir le soleil et unifie le teint.",
            "ete": "Après le soleil, hydratez votre peau matin et soir : c'est le secret d'un bronzage qui dure.",
            "automne": "L'automne est le moment idéal pour un soin réparateur après les agressions de l'été.",
        },
    },
    "garage": {
        "mots": ["garage", "automobile", "automobiles", "vehicules", "carrosserie", "mecanique", "pneus"],
        "libelle": "Garage automobile",
        "naf": ["45.20A", "45.20B"],
        "osm": [("shop", "car_repair")],
        "schema": "AutoRepair",
        "couleur": "#1f2937",
        "accroche": "Entretien, réparation, pneus, diagnostic : un garage indépendant, des prix clairs et des délais tenus.",
        "badges": ["Devis gratuit", "Toutes marques", "Garage indépendant"],
        "services": [
            ("Entretien", "Vidange, révision constructeur, filtres."),
            ("Freinage", "Plaquettes, disques, liquide de frein."),
            ("Pneus", "Montage, équilibrage, parallélisme."),
            ("Diagnostic", "Voyant allumé, valise électronique, préparation au contrôle technique."),
        ],
        "horaires": {"Lundi – Vendredi": "8h – 12h / 14h – 18h30", "Samedi": "8h – 12h", "Dimanche": "Fermé"},
        "conseils": {
            "hiver": "Pneus hiver ou 4 saisons : dans de nombreuses communes de montagne, ils sont obligatoires de novembre à mars.",
            "printemps": "Au printemps, faites contrôler votre climatisation avant les premières chaleurs.",
            "ete": "Avant un long trajet : pression des pneus, niveaux et freins. 10 minutes de contrôle pour partir serein.",
            "automne": "Vérifiez votre batterie avant l'hiver : c'est la première cause de panne au premier froid.",
        },
    },
    "macon": {
        "libelle": "Maçonnerie et construction",
        "mots": ["maconnerie", "macon", "construction", "genie civil", "gros oeuvre", "beton", "renovation", "transformation de batiments"],
        "naf": ["43.99C", "41.20A"], "osm": [("craft", "builder")], "schema": "GeneralContractor", "couleur": "#6b4f2a",
        "accroche": "Construction, rénovation et transformation : un maçon local, des délais tenus et un chantier propre.",
        "badges": ["Devis gratuit", "Travail soigné", "Entreprise locale"],
        "services": [("Rénovation", "Transformation et rénovation de maisons et d'appartements."),
                     ("Maçonnerie", "Murs, dalles, ouvertures, petits et gros travaux."),
                     ("Aménagements extérieurs", "Murets, terrasses, accès et pavage."),
                     ("Petits travaux", "Réparations et interventions rapides.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "L'hiver est le bon moment pour planifier vos travaux du printemps : les agendas se remplissent vite.",
                     "printemps": "Printemps = saison des chantiers extérieurs : pensez aux autorisations de construire à l'avance.",
                     "ete": "Un chantier d'été se prépare tôt : réservez votre créneau dès maintenant.",
                     "automne": "Avant le gel, faites vérifier les fissures de vos murs extérieurs pour éviter les infiltrations."}},
    "carreleur": {
        "libelle": "Carreleur",
        "mots": ["carrelage", "carreleur", "revetements de sols", "chape"],
        "naf": ["43.33Z"], "osm": [("craft", "tiler")], "schema": "HomeAndConstructionBusiness", "couleur": "#0f766e",
        "accroche": "Carrelage, faïence, sols et salles de bain : des finitions précises, posées par un artisan local.",
        "badges": ["Devis gratuit", "Finitions soignées", "Artisan local"],
        "services": [("Carrelage", "Pose de carrelage intérieur et extérieur."),
                     ("Salles de bain", "Faïence, douches à l'italienne, rénovation complète."),
                     ("Sols", "Chapes, revêtements, parquets et sols techniques."),
                     ("Terrasses", "Dallage et carrelage extérieur résistant au gel.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Pour l'extérieur, choisissez un carrelage résistant au gel : c'est indispensable en montagne.",
                     "printemps": "Une salle de bain se rénove en une à deux semaines : planifiez avant l'été.",
                     "ete": "Un joint abîmé laisse passer l'eau : faites-le refaire avant qu'il n'abîme le support.",
                     "automne": "Nettoyez et imperméabilisez votre terrasse avant l'hiver pour la protéger du gel."}},
    "paysagiste": {
        "libelle": "Paysagiste",
        "mots": ["paysagiste", "paysagisme", "jardin", "jardins", "jardinage", "espaces verts", "horticulture", "elagage"],
        "naf": ["81.30Z"], "osm": [("craft", "gardener")], "schema": "LandscapingBusiness", "couleur": "#15803d",
        "accroche": "Création et entretien de jardins : un paysagiste local pour des extérieurs beaux toute l'année.",
        "badges": ["Devis gratuit", "Entretien régulier", "Entreprise locale"],
        "services": [("Entretien", "Tonte, taille des haies, désherbage, entretien régulier."),
                     ("Création", "Aménagement de jardins, plantations, gazon."),
                     ("Élagage", "Taille et abattage d'arbres en toute sécurité."),
                     ("Aménagements", "Terrasses, dallages, murets et clôtures.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "L'hiver est idéal pour la taille des arbres fruitiers et la préparation de vos projets.",
                     "printemps": "C'est le moment de scarifier et de semer votre gazon pour un jardin vert tout l'été.",
                     "ete": "Arrosez tôt le matin ou tard le soir : moins d'évaporation, des plantes en meilleure santé.",
                     "automne": "L'automne est la meilleure saison pour planter arbres et arbustes."}},
    "nettoyage": {
        "libelle": "Entreprise de nettoyage",
        "mots": ["nettoyage", "nettoyages", "conciergerie", "entretien de batiments", "entretien de locaux", "lavage"],
        "naf": ["81.21Z"], "osm": [("shop", "dry_cleaning")], "schema": "HousekeepingService", "couleur": "#0284c7",
        "accroche": "Nettoyage de bureaux, d'appartements et fins de bail : un travail impeccable, des horaires flexibles.",
        "badges": ["Devis gratuit", "Horaires flexibles", "Entreprise locale"],
        "services": [("Fins de bail", "Nettoyage complet avec garantie de remise."),
                     ("Bureaux", "Entretien régulier de vos locaux professionnels."),
                     ("Particuliers", "Ménage régulier ou ponctuel."),
                     ("Vitres", "Nettoyage de vitres, stores et façades vitrées.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Le chauffage assèche l'air et fait voler la poussière : aérez 10 minutes chaque jour.",
                     "printemps": "Le grand nettoyage de printemps, c'est maintenant : vitres, stores et placards.",
                     "ete": "Vous déménagez ? Réservez votre nettoyage de fin de bail tôt : c'est la haute saison.",
                     "automne": "Avant l'hiver, nettoyez vitres et stores pour profiter de toute la lumière."}},
    "restaurant": {
        "libelle": "Restaurant",
        "mots": ["restaurant", "restauration", "cafe", "bar", "pizzeria", "traiteur", "snack", "kebab", "boulangerie", "patisserie", "food truck", "cuisine"],
        "naf": ["56.10A"], "osm": [("amenity", "restaurant"), ("amenity", "cafe")], "schema": "Restaurant", "couleur": "#b45309",
        "accroche": "Une cuisine faite maison, un accueil chaleureux : venez nous découvrir.",
        "badges": ["Fait maison", "Produits locaux", "À emporter"],
        "services": [("Sur place", "Une carte de saison dans un cadre convivial."),
                     ("À emporter", "Commandez par téléphone, récupérez sans attendre."),
                     ("Menu du jour", "Un menu différent chaque jour de la semaine."),
                     ("Événements", "Repas de groupe, anniversaires et apéritifs.")],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {"hiver": "Nos plats d'hiver sont de retour : venez vous réchauffer !",
                     "printemps": "Nouvelle carte de printemps avec les produits de saison.",
                     "ete": "La terrasse est ouverte : profitez des beaux jours avec nous.",
                     "automne": "La chasse et les produits d'automne arrivent à la carte."}},
    "transport": {
        "libelle": "Transport et déménagement",
        "mots": ["demenagement", "demenagements", "transport", "transports", "livraison", "logistique", "taxi", "coursier"],
        "naf": ["49.42Z"], "osm": [("shop", "moving")], "schema": "MovingCompany", "couleur": "#1d4ed8",
        "accroche": "Déménagements, transports et livraisons : ponctuels, soigneux et au juste prix.",
        "badges": ["Devis gratuit", "Assurance incluse", "Entreprise locale"],
        "services": [("Déménagements", "Particuliers et entreprises, avec ou sans emballage."),
                     ("Transports", "Transport de marchandises et d'objets volumineux."),
                     ("Débarras", "Vidage de caves, greniers et appartements."),
                     ("Livraisons", "Livraisons régionales rapides.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Déménager en hiver, c'est souvent moins cher et plus facile à réserver.",
                     "printemps": "Les fins de mois de printemps partent vite : réservez votre date à l'avance.",
                     "ete": "L'été est la haute saison des déménagements : réservez au moins un mois avant.",
                     "automne": "Profitez de l'automne pour débarrasser cave et grenier avant l'hiver."}},
    "informatique": {
        "libelle": "Services informatiques",
        "mots": ["informatique", "logiciel", "logiciels", "developpement web", "site internet", "sites web", "digital", "numerique", "reseaux informatiques"],
        "naf": ["62.02A"], "osm": [("shop", "computer")], "schema": "ProfessionalService", "couleur": "#4f46e5",
        "accroche": "Dépannage, installation et solutions informatiques pour les particuliers et les PME de la région.",
        "badges": ["Intervention rapide", "À domicile", "Entreprise locale"],
        "services": [("Dépannage", "Ordinateurs, imprimantes, réseaux, à domicile ou à distance."),
                     ("PME", "Installation, sauvegardes et maintenance de votre parc informatique."),
                     ("Sécurité", "Antivirus, sauvegardes et protection de vos données."),
                     ("Formation", "Prise en main de vos outils, à votre rythme.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Faites une sauvegarde complète de vos données : un disque dur ne prévient pas avant de lâcher.",
                     "printemps": "Grand ménage numérique : supprimez les logiciels inutiles, votre ordinateur vous dira merci.",
                     "ete": "En vacances, méfiez-vous des Wi-Fi publics : évitez d'y consulter votre banque.",
                     "automne": "Vérifiez vos mises à jour : elles corrigent des failles de sécurité importantes."}},
    "fitness": {
        "libelle": "Coach sportif",
        "mots": ["fitness", "coaching sportif", "coach", "salle de sport", "yoga", "pilates", "sport", "entrainement", "dietetique", "nutrition"],
        "naf": ["93.13Z"], "osm": [("leisure", "fitness_centre")], "schema": "HealthClub", "couleur": "#dc2626",
        "accroche": "Coaching personnalisé pour atteindre vos objectifs, à votre rythme.",
        "badges": ["Séance d'essai", "Programme sur mesure", "Coach diplômé"],
        "services": [("Coaching individuel", "Un programme adapté à vos objectifs et à votre niveau."),
                     ("Cours collectifs", "Des séances en petits groupes, motivantes et conviviales."),
                     ("Remise en forme", "Reprendre le sport en douceur et en sécurité."),
                     ("Nutrition", "Des conseils simples pour mieux manger au quotidien.")],
        "horaires": HORAIRES_BOUTIQUE,
        "conseils": {"hiver": "Le froid n'est pas une excuse : 20 minutes d'exercice à la maison suffisent pour garder le rythme.",
                     "printemps": "C'est le moment de reprendre : fixez-vous un objectif simple pour les 8 prochaines semaines.",
                     "ete": "Par forte chaleur, entraînez-vous tôt le matin et hydratez-vous bien.",
                     "automne": "La rentrée est le meilleur moment pour prendre de bonnes habitudes."}},
    "photographe": {
        "libelle": "Photographe",
        "mots": ["photographie", "photographe", "photo", "video", "videaste", "audiovisuel"],
        "naf": ["74.20Z"], "osm": [("craft", "photographer")], "schema": "ProfessionalService", "couleur": "#111827",
        "accroche": "Mariages, portraits, entreprises : des images qui racontent votre histoire.",
        "badges": ["Devis gratuit", "Retouches incluses", "Photographe local"],
        "services": [("Mariages", "Reportage complet de votre journée."),
                     ("Portraits", "Portraits, familles et photos professionnelles."),
                     ("Entreprises", "Photos de produits, d'équipes et de locaux."),
                     ("Vidéo", "Films courts pour vos réseaux sociaux.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Les séances photo d'hiver en extérieur donnent des lumières magnifiques : osez !",
                     "printemps": "Mariage cet été ? Les photographes se réservent maintenant.",
                     "ete": "La lumière du soir, une heure avant le coucher du soleil, est la plus flatteuse.",
                     "automne": "Les couleurs d'automne sont idéales pour les photos de famille."}},
    "generique": {
        "libelle": "Entreprise",
        "mots": [],
        "naf": [], "osm": [], "schema": "LocalBusiness", "couleur": "#334155",
        "accroche": "Une entreprise locale, sérieuse et joignable, au service de ses clients.",
        "badges": ["Devis gratuit", "Réponse rapide", "Entreprise locale"],
        "services": [("Nos prestations", "Présentez ici votre activité principale."),
                     ("Sur mesure", "Une solution adaptée à chaque client."),
                     ("Conseil", "Un interlocuteur unique qui prend le temps de vous écouter."),
                     ("Proximité", "Une entreprise de votre région, facile à joindre.")],
        "horaires": HORAIRES_ARTISAN,
        "conseils": {"hiver": "Nous restons à votre disposition tout l'hiver : n'hésitez pas à nous contacter.",
                     "printemps": "Le printemps est là : c'est le bon moment pour lancer vos projets.",
                     "ete": "Pensez à nous contacter avant les vacances pour planifier vos projets de la rentrée.",
                     "automne": "La rentrée est l'occasion de faire le point : parlons de vos besoins."}},
}

SAISONS = {12: "hiver", 1: "hiver", 2: "hiver", 3: "printemps", 4: "printemps", 5: "printemps",
           6: "ete", 7: "ete", 8: "ete", 9: "automne", 10: "automne", 11: "automne"}

EXCLUSIONS = ["holding", "participations", "prise de participation", "gestion de fortune", "gestion de patrimoine",
              "detention de", "en liquidation", "fondation", "association"]


def classer(texte):
    """Devine le métier à partir du but social ; None si l'entreprise n'est pas une cible."""
    from sources import normaliser
    t = normaliser(texte).lower()
    trouve = lambda mot: len(re.findall(r"\b" + re.escape(mot) + r"s?\b", t))  # noqa: E731
    if any(trouve(x) for x in EXCLUSIONS):
        return None
    scores = {m: sum(trouve(mot) for mot in v["mots"]) for m, v in METIERS.items()}
    meilleur = max(scores, key=lambda m: scores[m])
    return meilleur if scores[meilleur] else "generique"
